name: graphdta_venv
channels:
  - conda-forge
  - pytorch
dependencies:
  - conda-forge::python=3.7
  - conda-forge::pip
  - conda-forge::cudatoolkit=11.7.0
  - pytorch::pytorch=1.13.0
  - pytorch::torchvision=0.14.0
  - conda-forge::rdkit
  - pip:
      - numpy==1.21.2
      - pandas==1.3.5
      - torch-geometric==2.1.0.post1
      - requests==2.26.0
      - typing-extensions==4.3.0
      - pytorch_lightning==1.5.10
      - wandb==0.12.21
      - matplotlib==3.5.3
      - pytest==7.1.3
      - fastapi==0.85.0
      - pydantic==1.10.2
      - uvicorn==0.18.3
      - starlette==0.20.4
      - git+https://github.com/NVIDIA/dllogger.git